#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# Only need to add top-level role classes.
# All other classes are recursively included
mod 'yo61-profile',
  :git => 'git@github.com:robinbowes/vagrant-kafka-logging.git',
  :path => 'puppet/modules/profile'